package main

import (
       "encoding/json"
       "net/http"
       "log"
)



type AutoGenerated struct {
	Array []struct {
		EntityTitle       string `json:"entity_title"`
		EntityOrgName     string `json:"entity_org_name"`
		PossibleUserName  string `json:"possible_user_name"`
		PosibbleUserEmail string `json:"posibble_user_email"`
		UserPositionTitle string `json:"user_position_title"`
		MsgBodyID         int    `json:"msg_body_id"`
	} `json:"array"`
}
func parseJson(rw http.ResponseWriter, request *http.Request) {
    decodeJson := json.NewDecoder(request.Body)

    var msg AutoGenerated
    err := decodeJson.Decode(&msg)

    if err != nil {
        panic(err)
    }
    log.Println(msg.Array)
}

func main() {
    http.HandleFunc("/", parseJson)
    http.ListenAndServe(":1338", nil)
}
